### ISSUE TITLE
Callbacks: fitting

### ISSUE THREAD

**Issue by Tom-Willemsen** [ISISComputingGroup/ibex_bluesky_core#19]
As a user, I would like to be able to apply fits to scans.

This depends on https://github.com/ISISComputingGroup/ibex_bluesky_core/issues/8 , which should be merged before this is started.

This is relatively standard bluesky functionality that needs documenting/exposing in a nice way.

This should also include plotting the fit onto the same axes that are used by `LivePlot`, i.e. you should be able to get a result that looks something like this (obviously this is already possible using standard bluesky functionality - this is mostly a documentation exercise):

![image](https://github.com/user-attachments/assets/0083bb3a-90a8-4c62-8a9c-03559ed14703)

---

## Acceptance criteria
- [x] How to do fitting is documented
- [x] "standard" fit functions are exposed in a user-friendly way
  * Note: we may need to get scientists to agree on descriptions and parameter names for some of these models. E.g. width of a gaussian can be either described by standard deviation or variance, and may or may not include a "background" (y-offset) parameter. Even for trivial fits like "linear" - some people describe as `ax + b`, others as `mx + c` or `(c1)x + c0`. In order to avoid having overlapping models on different beamlines it would be best to get the science groups to all agree with a single set of definitions. Maybe we can re-use any existing conventions from mantid?
  * [x] Linear
  * [x] Polynomial
  * [x] Gaussian
  * [x] Lorentzian
  * [x] Damped oscillator
  * [x] Slit scan fit
  * [x] Erf (error function)
  * [x] Erfc (complementary error function)
  * [x] Top hat
  * [x] Trapezoid
  * [x] Centre of mass
    * Note: CoM is "special", it doesn't really fit a curve to the data directly
    * `bluesky` already has support for this via the `PeakStats` callback
- [x] Fitting is _not_ subscribed to the `RunEngine` by default
  * Instead, each plan will define a sensible fit for that type of scan.
- [x] The final parameters of the fit, including statistical fit parameters like r^2 or covariance matrices, are accessible to the user (via `plan_result` or similar mechanisms) after the scan has completed

### Discussed in planning 05/09/24
37:15

**Comment by Tom-Willemsen** [comment]
We _might_ need ability to dynamically guess initial fit parameters based on data collected so far. See existing scans library for how it's done there.

Although this isn't done by default in bluesky, it should generally be a reasonably simple addition in a thin wrapper over `LiveFit`.

**Comment by jackbdoughty** [comment]
See:
[ibex_bluesky_core PR](https://github.com/ISISComputingGroup/ibex_bluesky_core/pull/34/)
[release notes PR](https://github.com/ISISComputingGroup/IBEX/pull/8529)

**Comment by Tom-Willemsen** [comment]
For info, asked the scientists about point raised in code review (whether initial guess should be shown or not), and all present [RD/CK/JL] agreed it should be shown on the plot
