### ISSUE TITLE
Generate uncertainties from DAE counts data

### ISSUE THREAD

**Issue by Tom-Willemsen** [ISISComputingGroup/ibex_bluesky_core#21]
As a user, I would like to be able to access uncertainties on counts data from the DAE.

The raw uncertainty (standard deviation) of a counts measurement is given by `sqrt(counts)` (poisson counting statistics).

When summing _uncorrelated_ counts together or normalizing them, the uncertainties need to be propagated using standard rules which can be found e.g. [on wikipedia](https://en.wikipedia.org/wiki/Propagation_of_uncertainty#Example_formulae) or physics/statistics textbooks.

This issue depends on the user-facing implementation of the DAE in https://github.com/ISISComputingGroup/ibex_bluesky_core/issues/20

### Acceptance criteria

- [ ] For an individual spectrum, uncertainties are available.
- [x] For summed spectra (e.g. total detector counts), uncertainties are available, following standard uncertainty propagation rules.
- [x] For normalised counts (e.g. detector counts / monitor counts), uncertainties are available, following standard uncertainty propagation rules.
- [ ] The above functionality is general if possible, so that it _could_ be applied to devices other than the DAE in future.
  * However, DAE counts are the only thing which are _explicitly_ in scope for this issue.

Notes:
- Consider using a library like `scipp` which has a `numpy`-like interface but handles units and uncertainties by default under-the-hood.
  * `scipp` is being developed at ESS with past input from STFC, so is well suited for neutron counts data.
  * Or alternatively the `uncertainties` python package - but beware that it tracks correlations so may have bad scaling on "large" arrays like counts data from the DAE.
- If you need more information/background on uncertainties and error propagation, you can borrow the book on @Tom-Willemsen 's desk. 
- Using these uncertainties in plots & fits is out of scope for this issue - that is the subject of a future issue.
- The "simple" error propagation rules are only valid for uncorrelated variables. Do not use them if the variables are correlated.

### Discussed in planning 05/09/24
52:30

**Comment by jackbdoughty** [comment]
Deferred first criterion to a [new ticket](https://github.com/ISISComputingGroup/ibex_bluesky_core/issues/35) as it was getting too complicated for how useful it would be at this time.

**Comment by jackbdoughty** [comment]
[Ibex bluesky core PR](https://github.com/ISISComputingGroup/ibex_bluesky_core/pull/36)
[Release notes PR](https://github.com/ISISComputingGroup/IBEX/pull/8532)
