### ISSUE TITLE
Use uncertainties in plots and fits

### ISSUE THREAD

**Issue by Tom-Willemsen** [ISISComputingGroup/ibex_bluesky_core#22]
As a user, if uncertainties have been published by the underlying device, I would like plots & fits to use them.

This issue depends on all of:
- https://github.com/ISISComputingGroup/ibex_bluesky_core/issues/21
- https://github.com/ISISComputingGroup/ibex_bluesky_core/issues/19
- https://github.com/ISISComputingGroup/ibex_bluesky_core/issues/8

Which must be completed first.

### Acceptance criteria:
- [x] Uncertainties, if available, are plotted as error bars on plots.
  * We probably want a `LivePlotWithUncertainty` wrapper on top of `LivePlot` for this.
  * `matplotlib` can already handle plots with error bars, so this is largely "pass data through to matplotlib in the right places".
- [x] Uncertainties, if available, are used in fits. 
  * `lmfit` takes `weights` for each point which can be used to implement this - so this is largely "pass data through to lmfit in the right places".

**Comment by Tom-Willemsen** [comment]
When doing fitting, the weights of each point are `1/uncertainty`. Obviously this is problematic in the case where counts = uncertainty = 0.

I discussed this with the scientists in the scans meeting 2024/10/15 and agreed that when initially generating the uncertainties (in `read_spectrum_dataarray`), the uncertainties should be based on `sqrt(N + 0.5)` rather than `sqrt(N)` as per poisson counting statistics. This was agreed with CK, RD, JL present. The actual _data_ should still be zero, the `+0.5` is only for uncertainty calculation.

The above approach is both "smooth" and converges towards `sqrt(N)` in the limit with high counts.

When doing this ticket make sure we document the above approach (e.g. write an ADR for it)

**Comment by jackbdoughty** [comment]
[ibex_bluesky_core PR](https://github.com/ISISComputingGroup/ibex_bluesky_core/pull/64)
