### ISSUE TITLE
Initial test on an instrument (CRISP)

### ISSUE THREAD

**Issue by Tom-Willemsen** [ISISComputingGroup/ibex_bluesky_core#32]
- As a scientist I'd like to see and provide feedback on an initial version of the library
- As a developer I'd like to know how our bluesky scans behave on a real instrument

## Acceptance criteria

- [x] Run some relatively simple test scans on a real instrument
  * CRISP is a likely first candidate as not fully scheduled, but representative. Talk to CK.
  * The library will eventually be used across different science groups, but for _this_ ticket, testing on a single real instrument is sufficient
- [x] Test should cover:
  * [x] Using a block (e.g. scanning a motor would cover this)
    * Ideally try using multiple types of blocks, e.g. `BlockRw` and `BlockMot`.
  * [x] Using the DAE, including some kind of normalization to e.g. monitors or good frames
    * Ideally test both "one run per scan point" and "one period per scan point" modes, even if the instrument in question would only _actually_ use one of those modes
  * [x] Plotting the results of the scan
  * [x] Fitting the results of the scan (assuming https://github.com/ISISComputingGroup/ibex_bluesky_core/issues/19 is completed)
  * [x] Writing an output file (assuming https://github.com/ISISComputingGroup/ibex_bluesky_core/issues/7 is completed)
- [x] Feedback from test collected:
  * [x] What went well
  * [x] What didn't go well (ensure tickets exist for these things)
  * [x] Any missing functionality not covered by existing tickets / not noted explicitly in the [requirements document](https://stfc365.sharepoint.com/:w:/r/sites/ISISProject-1396/_layouts/15/doc2.aspx?sourcedoc=%7BB52537FC-BD78-469A-8D89-F73AA672516C%7D&file=SCANS%20Library%20Requirements.docx&wdLOR=c821F5C9B-E0BB-4EE1-A7FD-8623F9153142&action=default&mobileredirect=true)
  * [ ] Share feedback / notes / screenshots etc at the next scans library regular meeting after this test takes place

## Notes

Ensure we set expectations appropriately with scientists: this is an _initial, exploratory_ test of an _early version_ of the library. Problems, missing functionality, etc are expected, that is the point of this testing.

**Comment by jackbdoughty** [comment]
Configuration script we used for testing on CRISP: 
[crisp_bluesky.zip](https://github.com/user-attachments/files/17871712/crisp_bluesky.zip)

**Comment by Tom-Willemsen** [comment]
Test is substantively complete, was run on CRISP with CK and @jackbdoughty

Will keep in progress pending a review on Monday with more of the refl scientists.

---

Test scans on CRISP have been demo'd _directly_ to CK (Refl), MC (Refl), JL (Muons). 
- Overall feedback was very positive
  * CK comment is that this is already broadly comparable to, and in a few cases (e.g. adaptive scanning) better than, the existing scans library. Effectively giving sign-off that this library is at or near the point where it could replace the existing scans code for refl use-cases.
  * CK commented that performance of scans is much faster in bluesky than in the old scans code (likely due to e.g. reading detectors in parallel via asyncio - I also saw very substantial speedup from this on my dev machine)
- We were able to align a sample on CRISP, using bluesky. 
  * This is a core-use case for reflectometers.
- All of the major bits of functionality we've implemented worked
  * Tested a variety of scans on different reflectometry parameters & blocks
  * Tested the main DAE run modes: period per point & run per point, saving files or not
  * Plotting and fitting generally worked well, some usability feedback noted in issues below
  * File formats are generally fine at the moment (both the overall scans record and also the fit records)
- As all of the "simple" step scans worked rather easily, we also tried adaptive scans; these also worked well with minimal setup
- Scientists so far have been generally ok with `ctrl-c` behaviour and typing `RE()` around plans and other command-line syntax.
- Reflectometry instrument scripts install a _global_ python logging handler which causes a lot of messages to be printed to screen (only after using their instrument scripts)
  * Solution to this is to fix reflectometry scripts to not install a global handler, and to instead only install a handler on it's own messages.

---

Below is one normal step-scan, and one adaptive scan, of the same axis using the DAE in period mode on CRISP (notice the tight resampling over the gaussian region by the adaptive scan, giving good peak statistics for a reasonably low point cost):

![image](https://github.com/user-attachments/assets/bcfe914c-44eb-4b5a-b64c-a75fba7d9ed5)

Example command was:

```
RE(adaptive_scan(b.SAMPPHI, x-0.25, x+0.25, min_step=0.005, max_step=0.03, target_delta=0.002, frames=50, mon=1, det=3, model=fit.Gaussian()))
```

---

Issues have been generated as a result of this testing - mostly style/usability things rather than functional ones:
- https://github.com/ISISComputingGroup/ibex_bluesky_core/issues/69
- https://github.com/ISISComputingGroup/ibex_bluesky_core/issues/70
- https://github.com/ISISComputingGroup/ibex_bluesky_core/issues/72
- https://github.com/ISISComputingGroup/ibex_bluesky_core/issues/73 
- https://github.com/ISISComputingGroup/ibex_bluesky_core/issues/24 (comment added)

**Comment by Tom-Willemsen** [comment]
Since CK commented on scan performance I thought I would benchmark a representative scan on CRISP while I had access... (ignore the difference between PHI and SAMPPHI, it's scanning the same variable, that's an artefact of CRISP's refl setup...). Starting both from `PHI = x = 0.3`:

### Old scans code
```
start=time.time();crisp_scan(b.phi, x-0.25, x+0.25, 51, frames=10, fit=Gaussian);end=time.time()
213.7 seconds
```
### Bluesky
```
start=time.time();RE(scan(b.SAMPPHI, x-0.25, x+0.25, 51, frames=10, model=fit.Gaussian()));end=time.time()
137.3 seconds
```

### Theoretical
- Counting: 51 * 10 frames / 40 fps = 12.7 seconds
- Moving: ~4 seconds of movement time (accounting for repeated acceleration/deceleration of axis)

~16.7 secs total for a theoretically perfect version of this step scan

---

i.e. bluesky is a bit faster than old library (mostly due to more efficient CA usage), but still an order of magnitude off the physical limits
