### ISSUE TITLE
Periodic CI against `main` of `bluesky` and `ophyd-async`

### ISSUE THREAD

**Issue by Tom-Willemsen** [ISISComputingGroup/ibex_bluesky_core#49]
As a developer I would like an early preview if upstream changes to `bluesky` or `ophyd-async` might cause problems for us.

Run a periodic (nightly/weekly?) CI job which explicitly installs the `main` branch of both `bluesky` and `ophyd-async` (as opposed to released versions which we typically use), and run:
- `ruff/pyright`
- `pytest`

**Comment by rerpha** [comment]
may just have a crack at this for PD

**Comment by rerpha** [comment]
leaving open until we know it works

**Comment by rerpha** [comment]
https://github.com/ISISComputingGroup/ibex_bluesky_core/actions/runs/11828170080/job/32957754588 - proof of this working. closing this ticket.
