### ISSUE TITLE
DAE: add basic signals

### ISSUE THREAD

**Issue by Tom-Willemsen** [ISISComputingGroup/ibex_bluesky_core#9]
As a user I would like access to various typically-used configuration signals on the DAE.

Most signals which are settable via the "DAE configuration" screen in IBEX, or readable as "interesting" PVs from the DAE, should be in scope.

For this issue, the signals need to be added to the DAE ophyd-async device, as either "standard" or "configuration" signals as appropriate for each signal.

--- 

In scope:
- Most readable "interesting" float/int/str/enum PVs served directly from the DAE
  * Ensure this includes metadata like RB number, users, run number, ...
- Most writeable configuration float/int/str/enum PVs served by the DAE.
- Spectra, but limit to a single, constant "interesting" spectrum at a time for now
  * Prove we _can_ read a spectra data array, don't worry about details of how it will be used in practice in this issue.

Out of scope (for this issue):
- Derived signals (e.g. normalising intensity by monitor counts)
- Filtered signals (e.g. regions-of-interest on spectra)
- Anything that goes via areadetector (e.g. live view - this to be the subject of future issue(s))
- Higher-level logic, e.g. the exact sequence of bluesky messages to begin/acquire/end a data point at the "top level".

### Time in Planning
00:49:50 08/08/24

**Comment by rerpha** [comment]
https://github.com/ISISComputingGroup/IBEX/issues/8409 also add these PVs
